create or replace table f1_raw_data.event_schedule
(
    round_number int64,
    country string,
    location string,
    official_event_name string,
    event_date date,
    event_name string,
    event_format string,
    session_1 string,
    session_1_date timestamp,
    session_1_date_utc timestamp,
    session_2 string,
    session_2_date timestamp,
    session_2_date_utc timestamp,
    session_3 string,
    session_3_date timestamp,
    session_3_date_utc timestamp,
    session_4 string,
    session_4_date timestamp,
    session_4_date_utc timestamp,
    session_5 string,
    session_5_date timestamp,
    session_5_date_utc timestamp,
    f1_api_support boolean,
    season int64,
);